/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/login'
    | '/history'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/assessment' | '/login' | '/history' | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/assessment'
    | '/login'
    | '/_authenticated/history'
    | '/_authenticated/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
  }
}

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
